spring:
  application:
    name: cloud-order-service
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    fetch-registry: true
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true